name: 'Four Museum Recipe'
description: 'Adds the content types and fields Events'
type: 'Site'
install:
  - 'conditional_fields'
  - 'time_field'
  - 'four_museum_events'
config:
  # Allow config import to continue if config already exists.
  strict: true
  import:
    core: '*'
    field: '*'
    node: '*'
    paragraphs: '*'